### ISSUE TITLE
Keyboard input problem

### ISSUE THREAD

**Issue by kayatf** [immense/Remotely#369]
**Describe the bug**
Apparently some keyboard keys wont get sent if another keyboard layout than US QWERTY is utilized.

**To Reproduce**
1. Start any remote session
2. Try to type in an '@' or '/' sign with any other than an English (US, QWERTY) keyboard layout
3. See that it doesn't get sent

**Remotely Version**
Server: 2021.08.26.1335  
Agent: 2021.08.26.1335

**Expected Behavior**
'@' or '/' should be usable without utilising copy+paste.

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: =< 95.0.4638.54

**Comment by nnachtegael** [comment]
I solved this issue by showing and utilizing the on-board/on-screen keyboard on the remote host. It works on both windows and ubuntu remote hosts.

**Comment by nnachtegael** [comment]
I solved this issue by showing and typing in the on-board/on-screen keyboard on the remote host. Works on both windows and ubuntu remote hosts.

**Comment by yythoss** [comment]
Press alt + strg + @
Press alt + strg + \

**Comment by bitbound** [comment]
This issue has been grouped under pinned issue #688 .  Please comment there if you're still having issues in the latest release.
