### ISSUE TITLE
Middle Mouse Button Click Causes issues clicking on items and opening

### ISSUE THREAD

**Issue by SomeMex** [immense/Remotely#375]
**Describe the bug**
I am using the provided Remotely app, this is not self hosted. I am using Brave Browser, have also tested under chrome.

When I go to close a tab on a browser I use the middle mouse button (scroll wheel) to close. After trying this through the remotely app it suddenly prevents right click from working. Then when clicking with left click it starts to do the action that middle mouse click would do and it can't be undone.

**To Reproduce**
1. Go to any session and open remote control
2. Click the middle mouse button on a browser
3. Try to open a tab or bookmark or close the tab with middle mouse button.

**Remotely Version**
Server Version: 2021.09.25.0929:
Agent 2021.09.25.0929:

**Expected Behavior**
Be able to use middle mouse button use.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 (Remote Machine) - Accessing from Windows 10
 - Browser: Chrome & Brave
 - Version: Chrome: 95 - Brave: 1.31.87

**Additional Context**

**Comment by Web2FixOy** [comment]
Yes, the same issue here. 
When using the middle mouse click, which I use frequently as a shortcut for example to add delete a browser tab.
Behavior after mouse middle click:
After clicking using middle button of the mouse, in about 5 -15 seconds after the click the remote session becomes unresponsive.  

I found a workaround (for windows 10 remote machines):
I know this is not the correct way to solve the issue, but just to be able to get access to the remote machine again and being able to control that machine, use the "CTL +ALT + DEL" button from the admin panel's left menu, 
then try to move your mouse over the "Cancel" btn and click on "cancel"

Once done you can regain control over the remote pc.


#thank_you
#love_the_software

**Comment by moduletz** [comment]
Same issue here.

**Comment by MazixM** [comment]
Hi. Go to this file InputEventHandlers.js (https://github.com/immense/RemoteControl/blob/master/Server/wwwroot/src/InputEventHandlers.ts) and you can change code from: 
```
      if (e.button != 0 && e.button != 2) {
                return;
            }
```
to:
```
      if (e.button != 0 && e.button != 1 && e.button != 2) {
                return;
            }
```
That works for me.  
Its a bug and should be fixed..

**Comment by lucent-sea** [comment]
I'll add this in the next release.

**Comment by lucent-sea** [comment]
This should be fixed in the `experimental` tag:

```
docker pull immybot/remotely:experimental
```

I'll keep this open until the `latest` image is updated.  Probably next week.  I'll also do a GitHub release at the same time.
