### ISSUE TITLE
Use apache2?

### ISSUE THREAD

**Issue by FC2469** [immense/Remotely#401]
Hello, I have my server with apache2 and websites running, with ssl certificate and more functions. Changing server to nginx is not an option. How I can use server with apache2 instead of nginx?

**Comment by nexius76** [comment]
I've got Remotely run smoothly using a virtual host in apache2.
This is my vhost config as site-availeable/enabled

`<VirtualHost *:80>
        ServerName remotely.example.com
        ServerAlias remotely2.example.com *.example.com
        ServerAdmin support@example.com

        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /(.*)           ws://localhost:5000/$1 [P,L]
        RewriteCond %{HTTP:Upgrade} !=websocket [NC]
        RewriteRule /(.*)           http://localhost:5000/$1 [P,L]

        ProxyPreserveHost On
        <LocationMatch "/">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://localhost:5000/
        </LocationMatch>
        <Location "/BrowserHub">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://localhost:5000/
        </Location>

        <LocationMatch "/AgentHub">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://localhost:5000/
        </LocationMatch>

        <LocationMatch "/ViewerHub">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://localhost:5000/
        </LocationMatch>

        <LocationMatch "/CasterHub">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://localhost:5000/
        </LocationMatch>

        ErrorLog ${APACHE_LOG_DIR}/remotely.example.com-error.log
        CustomLog ${APACHE_LOG_DIR}/remotely.example.com-access.log combined
</VirtualHost>`

Adapt the virtualhost to your SSL needs.

**Comment by FC2469** [comment]
Thank you

**Comment by nexius76** [comment]
I've got Remotely run smoothly using a virtual host in apache2.
This is my vhost config as site-availeable/enabled

` <VirtualHost *:80>
        ServerName remotely.example.com
        ServerAlias remotely2.example.com *.example.com
        ServerAdmin support@example.com

        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /(.*)           ws://localhost:5000/$1 [P,L]
        RewriteCond %{HTTP:Upgrade} !=websocket [NC]
        RewriteRule /(.*)           http://localhost:5000/$1 [P,L]

        ProxyPreserveHost On
        <LocationMatch "/">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://localhost:5000/
        </LocationMatch>
        <Location "/BrowserHub">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://localhost:5000/
        </Location>

        <LocationMatch "/AgentHub">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://localhost:5000/
        </LocationMatch>

        <LocationMatch "/ViewerHub">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://localhost:5000/
        </LocationMatch>

        <LocationMatch "/CasterHub">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://localhost:5000/
        </LocationMatch>

        ErrorLog ${APACHE_LOG_DIR}/remotely.example.com-error.log
        CustomLog ${APACHE_LOG_DIR}/remotely.example.com-access.log combined
</VirtualHost> `

Adapt the virtualhost to your SSL needs.

**Comment by nexius76** [comment]
> I've got Remotely run smoothly using a virtual host in apache2. This is my vhost config as site-availeable/enabled
> 
> ` <VirtualHost *:80> ServerName remotely.example.com ServerAlias remotely2.example.com *.example.com ServerAdmin [support@example.com](mailto:support@example.com)
> 
> ```
>     RewriteEngine On
>     RewriteCond %{HTTP:Upgrade} =websocket [NC]
>     RewriteRule /(.*)           ws://localhost:5000/$1 [P,L]
>     RewriteCond %{HTTP:Upgrade} !=websocket [NC]
>     RewriteRule /(.*)           http://localhost:5000/$1 [P,L]
> 
>     ProxyPreserveHost On
>     <LocationMatch "/">
>             ProxyPass http://localhost:5000/
>             ProxyPassReverse http://localhost:5000/
>     </LocationMatch>
>     <Location "/BrowserHub">
>             ProxyPass http://localhost:5000/
>             ProxyPassReverse http://localhost:5000/
>     </Location>
> 
>     <LocationMatch "/AgentHub">
>             ProxyPass http://localhost:5000/
>             ProxyPassReverse http://localhost:5000/
>     </LocationMatch>
> 
>     <LocationMatch "/ViewerHub">
>             ProxyPass http://localhost:5000/
>             ProxyPassReverse http://localhost:5000/
>     </LocationMatch>
> 
>     <LocationMatch "/CasterHub">
>             ProxyPass http://localhost:5000/
>             ProxyPassReverse http://localhost:5000/
>     </LocationMatch>
> 
>     ErrorLog ${APACHE_LOG_DIR}/remotely.example.com-error.log
>     CustomLog ${APACHE_LOG_DIR}/remotely.example.com-access.log combined
> ```
> 
> `
> 
> Adapt the virtualhost to your SSL needs.

Sorry but I'm not able to insert the whole configuration code inside between the "`" to permit copy of text... :-(
