### ISSUE TITLE
consider using jpeg compression or zip compression to improve packet sending optimization (jpeg is better because the frame becomes much lighter).

### ISSUE THREAD

**Issue by SoftwareMagicIT** [immense/Remotely#404]
Hi, I saw that the system generally has a lot of performance, but compared to other software such as anydesk or teamviewer it is a bit harsh in responsiveness and uses bandwidth around 2mbps on fullHD screens. Until a couple of years ago I was developing my solution, only time was always short and the parts to fix too many. So I decided to use yours. Taking a look at the code I would say that it is the only flaw. Also a 500ms timeout is too high. Normally the desktop acquisition should travel between 15 and 30 frames / second, furthermore, to further improve performance, only the changed screen parts are captured and sent as single frames (for this reason, all other software also slow down in the presence of video).

**Comment by bitbound** [comment]
JPEG compression is already being used, as well as diffing of changed regions.
