### ISSUE TITLE
error configuration smtp

### ISSUE THREAD

**Issue by 1802932** [immense/Remotely#445]
I am with problem in configuration SMTP, but I am following the configuration's google. I put the information example, but I am putting this way.

return; No address found.

at MimeKit.InternetAddress.TryParse(ParserOptions options, Byte[] text, Int32& index, Int32 endIndex, Int32 groupDepth, AddressParserFlags flags, InternetAddress& address) at MimeKit.MailboxAddress.Parse(ParserOptions options, String text) at Remotely.Server.Services.EmailSenderEx.SendEmailAsync(String toEmail, String replyTo, String subject, String htmlMessage, String organizationID) in D:\a\1\s\Server\Services\EmailSender.cs:line 36

![Screenshot](https://user-images.githubusercontent.com/67167482/149398044-db1375ef-7537-42ba-9e7c-d11df3792616.png)

**Comment by 1802932** [comment]
I dont ideia with resolve this problem. 

I am using docker, This can be the problem?

**Comment by 1802932** [comment]
"SmtpDisplayName": "Atendimento",
    "SmtpEmail": "helpdesk@gmail.com",
    "SmtpHost": "smtp@gmail.com",
    "SmtpLocalDomain": "",
    "SmtpCheckCertificateRevocation": true,
    "SmtpPassword": "Mypassword",
    "SmtpPort": 587,
    "SmtpUserName": "helpdesk@gmail.com",


Follow my configuration

**Comment by 1802932** [comment]
Error | 01/17/2022 17:17:14 +00:00 | No address found. | MimeKit | at MimeKit.InternetAddress.TryParse(ParserOptions options, Byte[] text, Int32& index, Int32 endIndex, Int32 groupDepth, AddressParserFlags flags, InternetAddress& address) at MimeKit.MailboxAddress.Parse(ParserOptions options, String text) at Remotely.Server.Services.EmailSenderEx.SendEmailAsync(String toEmail, String replyTo, String subject, String htmlMessage, String organizationID) in D:\a\1\s\Server\Services\EmailSender.cs:line 72
-- | -- | -- | -- | --

**Comment by stevesobol** [comment]
Hi! I hadn't answered yet, because I kept looking at the information you provided, but couldn't find anything wrong.

I finally saw it.

`"SmtpHost": "smtp@gmail.com",`

That should probably be smtp.gmail.com - it's a hostname, not an email address.

**Comment by 1802932** [comment]
I am sorry, but in example I put wrong, but in server is smtp.gmail.com, but dont function. I use remotely in docker, is it necessary configure email in sendmail or other service the email in linux before? 

Because I search in group but not show me other configuration.

**Comment by 1802932** [comment]
Do I need to put some certificate in server about email?

**Comment by stevesobol** [comment]
The error message doesn't sound like it has anything to do with certificates. What does Google's online documentation say about that error?

**Comment by 1802932** [comment]
Nothing, I didn't find nothing that help me. To be better a new installation whitout docker? because already installed twice.

**Comment by 1802932** [comment]
Error | 01/19/2022 01:56:01 +00:00 | Resource temporarily unavailable | System.Net.NameResolution | at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses) at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__27_2(Object s) at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) --- End of stack trace from previous location --- at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken) at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken) at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken) at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken) at Remotely.Server.Services.EmailSenderEx.SendEmailAsync(String toEmail, String replyTo, String subject, String htmlMessage, String organizationID) in D:\a\1\s\Server\Services\EmailSender.cs:line 52
-- | -- | -- | -- | --

**Comment by 1802932** [comment]
Problem solve. 
I didnt make the file appsettings.Production.json, after that I made solve.

**Comment by 1802932** [comment]
Problem solve.
I didnt make the file appsettings.Production.json, after that I made solve.

**Comment by NOTORIOUSVR** [comment]
Hello - I have the exact same issue when attempting to configure SMTP (gmail also in this case) and I get the same error as above.

Also running in Docker
