### ISSUE TITLE
await in Async code

### ISSUE THREAD

**Issue by samuel-mr** [immense/Remotely#462]
From [this code](https://github.com/immense/Remotely/blob/master/Server/Components/Devices/Terminal.razor.cs#L135) 
```
   private void AppState_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            if (e.PropertyName == nameof(AppState.TerminalLines))
            {
                InvokeAsync(StateHasChanged);
```
Why don't you  use 'await' ? ` await InvokeAsync(StateHasChanged);` I understand your current code might cause unwanted side effects

**Comment by lucent-sea** [comment]
This is an event handler.  Since it can't return a `Task`, changing it to an async method and awaiting `InvokeAsync` will have no effect on the calling code.  So it's a non-issue.
