### ISSUE TITLE
remotely.one link is not available

### ISSUE THREAD

**Issue by hmirheydari** [immense/Remotely#476]
`remotely.one`  is not available

**Comment by stevesobol** [comment]
The company that took over the Remotely project from @lucent-sea is committed to improving Remotely and keeping it open-source. They're working on bringing on more developers.

The project is still up and running, just stalled (for the moment). Not sure what's going to happen with the website yet.

[Click here for more details.](https://github.com/immense/Remotely/discussions/472)
