### ISSUE TITLE
Website http://remotely.one is not accessible 

### ISSUE THREAD

**Issue by Web2FixOy** [immense/Remotely#478]
Hello,
The website Remotely.one is no longer accessible, it has been down for a while and I hope that it can be fixed.

Note: I did not know where to report this issue! so I decided to give this a shot, hope this does not raise many hates from other users that this is not a project issue as I am well aware of that.

Many thanks for the project and the hard work!

**Comment by stevesobol** [comment]
https://github.com/immense/Remotely/discussions/472

https://github.com/immense/Remotely#readme
