### ISSUE TITLE
GET request on API delivers data, although the authorization header is invalid

### ISSUE THREAD

**Issue by chr33z** [immense/Remotely#495]
**Describe the bug**
When using an invalid auhorization header to access the API, the API should prevent access to the data. Instead is shows a status of 403, but delivers the data anyway.

**To Reproduce**
Perform GET request on "api/Devices" with a valid organisation id, but an invalid auhorization header. This will deliver a list of all available devices, despite showing a 403 status.

**Remotely Version**
Server: latest

**Expected Behavior**
The API should not deliver data when the authorization header is invalid

**Comment by lucent-sea** [comment]
Thanks for fixing this.  This was a bad one.
