### ISSUE TITLE
Issues with latest update

### ISSUE THREAD

**Issue by WC3D** [immense/Remotely#503]
I installed the latest update on Ubuntu 22.04 Server and installed DotNet SDK 6.0. 

When in the WebUI any time I click save or make changes nothing saves or stays configured. I"m new to Linux and I may have made a mistake but this worked prior to this version.

**Remotely Version**
Server v2022.08.02.0428 

**Expected Behavior**
Be able to save the org name, or see connected devices. no setting stick

**Desktop (please complete the following information):**
 - OS: macOS 12.5 (INTEL)
 - Browser Google Chrome
 - Version 103.0.5060.134

**Comment by hst-tutorials** [comment]
I experienced this too, apparently the changes get written to appsettings.json, but are only applied, as soon as the server is restarted.

**Comment by joshua-russell** [comment]
This issue persists. Furthermore, according to the documentation you can create appsettings.Production.json and configure it the way you want - however after a reboot the web UI still uses appsettings.json.

**Comment by osnipezzini** [comment]
here is the same

**Comment by lucent-sea** [comment]
This should be fixed in the latest image in the new repo (https://hub.docker.com/r/immybot/remotely).
