### ISSUE TITLE
Server options need restart to take effect

### ISSUE THREAD

**Issue by leifnel** [immense/Remotely#519]
**Describe the bug**
Server options need restart to take effect

**To Reproduce**
When changing server options, saving, then going to another menu option and back to server options, the values before changing 
is shown, and the changes does not take effect. However, when looking at appsettings.json, the new values have been set.
To have the setting take effect, the container need to be restarted.

**Remotely Version**
Server (can be found on about page):  2022.08.02.0428
Agent (can be found in device card): N/A

**Expected Behavior**
Settings to take effect when saving, or at least there should be an "apply" button to reload the server to read the new options

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser [e.g. chrome, safari] Chrome

**Additional Context**
Server is running in Docker on Linux

**Comment by thaidv8x** [comment]
thank for your note. This exactly my problem.

**Comment by lucent-sea** [comment]
This should be fixed in the latest images in the new repo (https://hub.docker.com/r/immybot/remotely).
