### ISSUE TITLE
Update docker version to latest release

### ISSUE THREAD

**Issue by ulysserevient** [immense/Remotely#525]
Hi,
Is it possible to update docker version to the latest release ?
Thx

**Comment by thaidv8x** [comment]
yes, please update the docker version to lastest. I can't change anything in "server config" section.

**Comment by firestrife23** [comment]
Wondering about that too... :( or at least provide Dockerfile for build.

**Comment by lucent-sea** [comment]
The latest images are now being published here:  https://hub.docker.com/r/immybot/remotely
