### ISSUE TITLE
Portable Instant Support Clients defaults to http and not https

### ISSUE THREAD

**Issue by jakes670** [immense/Remotely#547]
**Is your feature request related to a problem? Please describe.**
Related to problem when using the Portable Instant Support Clients.

**Describe the solution you'd like**
The Portable Instant Support Clients must redirect to the URL that is used for the download
Eg. I am using a HA reverse proxy https://remotely.domain.com/ to host
When I open the EXE the URL in the remote server show  http://remotely.domain.com/ 
Somehow the https is changed to http

In the server log I see the below error

[Warning] [RequestPath:/_blazor/negotiate RequestId:0HMNBSTK6NH9O:00000002 - ConnectionId:0HMNBSTK6NH9O - Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware] | Message: Failed to determine the https port for redirect. | Exception:

**Describe alternatives you've considered**
I used the resident agents and that worked but, does not ask the remote user for consent. 

**Additional context**
None

**Comment by lucent-sea** [comment]
This will be fixed in the next release, assuming `RedirectToHttps` is set to `true` in `appsettings.json` (i.e. Server Config).

**Comment by DeAlexPesh** [comment]
![image](https://user-images.githubusercontent.com/16735261/212318877-38e5532b-0c9a-4317-af06-d2a48ae63e71.png)
not work
