### ISSUE TITLE
Trusted Proxies not Working for NGINX

### ISSUE THREAD

**Issue by iTABHayden** [immense/Remotely#559]
I don't believe this Remotely is setting the right headers for NGINX when the Nginx Proxy Manager proxy IP is set as a trusted proxy.

Is anyone else experiencing this? I can get other services accepting these OK.

Remotely version: 2023.01.06.1648

**Comment by iTABHayden** [comment]
Hi @lucent-sea

I don't believe this is working. I can get other apps reading the headers correctly but remotely just won't. My setup is Firewall>NPM>Remotely

I have added NPM address to the trusted proxies section in Remotely and even after a restart I am presented with this 
![image](https://user-images.githubusercontent.com/114112461/212273333-2ad792d0-6b80-4868-8cd5-23a0ffc5339f.png)

I have my docker compose stack bridged so the IP range is what is in the source code, 172.17.0.1
![image](https://user-images.githubusercontent.com/114112461/212273649-e513d49c-e1c6-444a-b7b0-56da70a82019.png)

I believe this is a correct config. NPM is defiantly forwarding the headers and I have ServiceDesk Plus and Blueiris reading them wihtout issues.

**Comment by lucent-sea** [comment]
FYI.  It's best to start a bug report with the specific symptoms you're experiencing, then give as much detail as possible about your environment and actions taken that led to the symptoms presenting.  A guess at what is not working isn't helpful for troubleshooting.

You highlighted the public IP address.  Is that not what you expect it to be?  Is that the issue?

> I don't believe this Remotely is setting the right headers for NGINX
This is correct and is the way it should be.  Remotely (i.e. ASP.NET Core) doesn't set request headers.  It receives the request from the reverse proxy and processes the request headers.

> Firewall>NPM>Remotely
> I have added NPM address to the trusted proxies section 
`172.71.88.134` is a Cloudflare IP address.  I'm guessing that's your firewall?  That will also need to be added to `KnownProxies`, and Cloudflare will need to be setting the appropriate headers.

If it's still not working as expected, I don't think it's an issue with Remotely.  All Remotely does is enable ASP.NET Core's built-in middleware.  I also doubt it's a bug in ASP.NET Core's middleware.  My guess is it's a configuration issue between Cloudflare and Nginx related to forwarding headers through two proxies.  There might be people on Reddit or other forums who can help with the necessary configuration.
