### ISSUE TITLE
The project is alive and well?

### ISSUE THREAD

**Issue by DeAlexPesh** [immense/Remotely#560]
last upgrade in 2021 year?

**Comment by tedtms** [comment]
I... what? The Releases page has an update from as early as _last week_.

![image](https://user-images.githubusercontent.com/49801453/212213715-c512c201-2c2f-449c-adf3-619aaae36c5c.png)

**Comment by lucent-sea** [comment]
I've made some updates recently.  I'm guessing there will be an update to the official roadmap soon.
