### ISSUE TITLE
Portable client redirects to http not https

### ISSUE THREAD

**Issue by jakes670** [immense/Remotely#564]
Is your feature request related to a problem? Please describe.
Related to problem when using the Portable Instant Support Clients.

Describe the solution you'd like
The Portable Instant Support Clients must redirect to the URL that is used for the download
Eg. I am using a HA reverse proxy https://remotely.domain.com/ to host
When I open the EXE the URL in the remote server show http://remotely.domain.com/
Somehow the https is changed to http

In the server log I see the below error

Info	01/15/2023 12:50:34 +00:00	
[Information] [RequestPath:/api/branding/4a296452-a428-44d7-96cc-5a5069aec535 RequestId:0HMNMUORLDQEV:00000002 - ConnectionId:0HMNMUORLDQEK - Microsoft.AspNetCore.Hosting.Diagnostics] | Message: Request finished HTTP/1.1 GET http://remote.domain.com/api/branding/4a296452-a428-44d7-96cc-5a5069aec535 - - - 200 - application/json;+charset=utf-8 445.2786ms | Exception:
Info	01/15/2023 12:50:34 +00:00	
[Information] [RequestPath:/api/branding/4a296452-a428-44d7-96cc-5a5069aec535 RequestId:0HMNMUORLDQEV:00000002 - ConnectionId:0HMNMUORLDQEK - Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware] | Message: Response:
StatusCode: 200
Content-Type: application/json; charset=utf-8
Date: Sun, 15 Jan 2023 12:50:33 GMT
Server: Kestrel
Transfer-Encoding: chunked | Exception:
Info	01/15/2023 12:50:34 +00:00	
[Information] [RequestPath:/api/branding/4a296452-a428-44d7-96cc-5a5069aec535 RequestId:0HMNMUORLDQEV:00000002 - ConnectionId:0HMNMUORLDQEK - Microsoft.AspNetCore.Routing.EndpointMiddleware] | Message: Executed endpoint 'Remotely.Server.API.BrandingController.Get (Remotely_Server)' | Exception:
Info	01/15/2023 12:50:34 +00:00	
[Information] [RequestPath:/api/branding/4a296452-a428-44d7-96cc-5a5069aec535 RequestId:0HMNMUORLDQEV:00000002 - ConnectionId:0HMNMUORLDQEK - Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker] | Message: Executed action Remotely.Server.API.BrandingController.Get (Remotely_Server) in 137.8581ms | Exception:
Info	01/15/2023 12:50:33 +00:00	
[Information] [Remotely.Server.API.BrandingController.Get (Remotely_Server) - ConnectionId:0HMNMUORLDQEK - Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor] | Message: Executing ObjectResult, writing value of type 'Remotely.Shared.Models.BrandingInfo'. | Exception:
Info	01/15/2023 12:50:33 +00:00	
[Information] [Remotely.Server.API.BrandingController.Get (Remotely_Server) - ConnectionId:0HMNMUORLDQEK - Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker] | Message: Route matched with {action = "Get", controller = "Branding", page = "", area = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Remotely.Shared.Models.BrandingInfo] Get(System.String) on controller Remotely.Server.API.BrandingController (Remotely_Server). | Exception:
Info	01/15/2023 12:50:33 +00:00	
[Information] [RequestPath:/api/branding/4a296452-a428-44d7-96cc-5a5069aec535 RequestId:0HMNMUORLDQEV:00000002 - ConnectionId:0HMNMUORLDQEK - Microsoft.AspNetCore.Routing.EndpointMiddleware] | Message: Executing endpoint 'Remotely.Server.API.BrandingController.Get (Remotely_Server)' | Exception:
Info	01/15/2023 12:50:33 +00:00	
[Information] [RequestPath:/api/branding/4a296452-a428-44d7-96cc-5a5069aec535 RequestId:0HMNMUORLDQEV:00000002 - ConnectionId:0HMNMUORLDQEK - Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware] | Message: Request:
Protocol: HTTP/1.1
Method: GET
Scheme: http
PathBase:
Path: /api/branding/4a296452-a428-44d7-96cc-5a5069aec535
Host: remote.domain.com | Exception:

![image](https://user-images.githubusercontent.com/31097840/212541710-fe789340-f73b-41a3-9541-a72c8f17b30d.png)

contents of appsettings.json
"RedirectToHttps": true

root@remote:/var/www/remotely# cat appsettings.json
{
  "ConnectionStrings": {
    "PostgreSQL": "Host=localhost;Database=Remotely;Username=postgres;",
    "SQLite": "DataSource=/remotely-data/Remotely.db",
    "SQLServer": "Server=(localdb)\\mssqllocaldb;Database=Remotely-Server-53bc9b9d-9d6a-45d4-8429-2a2761773502;Trusted_Connection=True;MultipleActiveResultSets=true"
  },
  "Logging": {
    "LogLevel": {
      "Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware": "Information",
      "Default": "Information"
    }
  },
  "ApplicationOptions": {
    "AllowApiLogin": false,
    "BannedDevices": [],
    "DataRetentionInDays": 90,
    "DBProvider": "SQLite",
    "EnableWindowsEventLog": true,
    "EnforceAttendedAccess": false,
    "KnownProxies": [
      "172.16.11.1"
    ],
    "MaxConcurrentUpdates": 10,
    "MaxOrganizationCount": 1,
    "MessageOfTheDay": "",
    "RedirectToHttps": true,
    "RemoteControlNotifyUser": true,
    "RemoteControlRequiresAuthentication": true,
    "RemoteControlSessionLimit": 3,
    "Require2FA": false,
    "SmtpDisplayName": "",
    "SmtpEmail": "",
    "SmtpHost": "",
    "SmtpLocalDomain": "",
    "SmtpCheckCertificateRevocation": false,
    "SmtpPassword": "",
    "SmtpPort": 587,
    "SmtpUserName": "",
    "Theme": "Dark",
    "TrustedCorsOrigins": [],
    "UseHsts": true,
    "UseHttpLogging": true
  }

**Comment by DeAlexPesh** [comment]
https://github.com/immense/Remotely/issues/547

**Comment by lucent-sea** [comment]
See [this comment](https://github.com/immense/Remotely/issues/573#issuecomment-1401989092).  Closing as duplicate.
