### ISSUE TITLE
Manjaro Deepin 22.0 Client Machine

### ISSUE THREAD

**Issue by freebs65** [immense/Remotely#569]
**To Reproduce**
1. Simply try and Remote Control the Machine
2. Machine shows as online
3. No errors

**Remotely Version**
Remotely Server Version: 2023.01.17.1852 running on Ubuntu 22.04 in docker container
Agent  see image: https://imgur.com/3Xo5phO

**Expected Behavior**
Trying to reach Home PC running Manjaro and it does nothing.
Says connectiong but will never connects.

**Desktop (please complete the following information):**
 - OS: Manjaro Deepin 22.0.0
 - Browser Vivaldi or Chrome]
 - Version Vivaldi 5.6.2867.58 - Chrome 109.0.5414.74

Was working on previous version of of Remotely version 21

Wondering if anyone else has an issue ?

**Additional Context**

**Comment by CJ1169** [comment]
I also have this issue.
[remotely-agent-log.txt](https://github.com/immense/Remotely/files/10495274/remotely-agent-log.txt)
attached log. 

Only discernible error is `pam_systemd_home(sudo:session): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.` which shouldn't be a show-stopper.

While not technically a completely fresh install, I did delete `/usr/local/bin/Remotely/` before installing the docker image fresh and using the Manjaro Install Script. Running Arch Linux.

`Linux [my computer] 6.1.6-arch1-3 #1 SMP PREEMPT_DYNAMIC Mon, 16 Jan 2023 12:51:23 +0000 x86_64 GNU/Linux`

**Comment by WMT-IT** [comment]
I'm receiving the same error with a EndeavourOS Arch Linux VM: 

System Details:
Operating System: EndeavourOS
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 6.1.8-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 4 × Common KVM processor
Memory: 3.8 GiB of RAM
Graphics Processor: llvmpipe
Manufacturer: QEMU
Product Name: Standard PC (i440FX + PIIX, 1996)
System Version: pc-i440fx-7.1


systemctl stats log from when i try to connect:
````
Feb 13 14:39:44 TMPLT-EOS sudo[1348]: pam_unix(sudo:session): session opened for user ity(uid=1000) by (uid=0)
Feb 13 14:39:44 TMPLT-EOS Remotely_Desktop[1349]: [X11Platform] SMLib/ICELib reported a new error: SESSION_MANAGER environment variable not defined
Feb 13 14:39:44 TMPLT-EOS Remotely_Desktop[1349]: [OpenGL] Unable to initialize GLX-based rendering: 'Avalonia.OpenGL.OpenGlException: Renderer 'llvmpipe (LLVM 15.0.7, 128 bits)' is blacklisted by 'llvmpipe'
                                                     at Avalonia.X11.Glx.GlxDisplay..ctor(X11Info x11, IList`1 probeProfiles) in /_/src/Avalonia.X11/Glx/GlxDisplay.cs:line 103
                                                     at Avalonia.X11.Glx.GlxPlatformOpenGlInterface.TryCreate(X11Info x11, IList`1 glProfiles) in /_/src/Avalonia.X11/Glx/GlxPlatformFeature.cs:line 34'
Feb 13 14:44:14 TMPLT-EOS Remotely_Agent[308]: info: Remotely.Agent.Services.AppLauncherLinux[0]
Feb 13 14:44:14 TMPLT-EOS Remotely_Agent[308]:       Attempting to launch screen caster with username ity, xauthority /home/ity/.Xauthority, display :0, and args -u ity /usr/local/bin/Remotely/Desktop/Remotely_Desktop --mode Unattended --host http://206.210.37.191:5000 --requester-name "" --org-name "White Mountain Paper Co." --org-id "739010d3-1ddf-4503-af00-a9ab08146e0f" --session-id "3f03399e-6559-4c29-a2b8-ea2479b67752" --access-key "HKFeamjZDboyB3f1G01Lg9XdviadCaG4Zas4GScqKtNNLjQnCyN3WnMnOsoDCs86".
Feb 13 14:44:14 TMPLT-EOS sudo[1596]:     root : PWD=/usr/local/bin/Remotely ; USER=ity ; COMMAND=/usr/local/bin/Remotely/Desktop/Remotely_Desktop --mode Unattended --host http://206.210.37.191:5000 --requester-name  --org-name White Mountain Paper Co. --org-id <REMOVED> --session-id 3f03399e-6559-4c29-a2b8-ea2479b67752 --access-key <REMOVED>
Feb 13 14:44:14 TMPLT-EOS sudo[1596]: pam_systemd_home(sudo:session): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
Feb 13 14:44:14 TMPLT-EOS sudo[1596]: pam_unix(sudo:session): session opened for user ity(uid=1000) by (uid=0)
Feb 13 14:44:14 TMPLT-EOS Remotely_Desktop[1597]: [X11Platform] SMLib/ICELib reported a new error: SESSION_MANAGER environment variable not defined
Feb 13 14:44:15 TMPLT-EOS Remotely_Desktop[1597]: [OpenGL] Unable to initialize GLX-based rendering: 'Avalonia.OpenGL.OpenGlException: Renderer 'llvmpipe (LLVM 15.0.7, 128 bits)' is blacklisted by 'llvmpipe'
                                                     at Avalonia.X11.Glx.GlxDisplay..ctor(X11Info x11, IList`1 probeProfiles) in /_/src/Avalonia.X11/Glx/GlxDisplay.cs:line 103
                                                     at Avalonia.X11.Glx.GlxPlatformOpenGlInterface.TryCreate(X11Info x11, IList`1 glProfiles) in /_/src/Avalonia.X11/Glx/GlxPlatformFeature.cs:line 34'


````

**Comment by WMT-IT** [comment]
Sounds like some sort of X11 update or issue then. 

I'm able to see the clients within the Remotely Server (Running as Docker Container within Unraid). But when i try to remote into them nothing happens.

My Windows 10 test clients are showing up just fine as well, and i can remote into them without issue. 

So I think it's the issue lies mainly within the Linux Client itself

**Comment by itopie** [comment]
> Sounds like some sort of X11 update or issue then.

You may be right. 

My guess, this is around SESSION_MANAGER environment variable : 

`fév 15 15:57:48 pc2015 Remotely_Desktop[8124]: [X11Platform] SMLib/ICELib reported a new error: SESSION_MANAGER environment variable not defined`

On the client where Remotely doesn't work, the variable is indeed empty. On my laptop (also Debian 10+KDE), the variable says:

local/[PC hostname]:@/tmp/.ICE-unix/16248,unix/[PC hostname]:/tmp/.ICE-unix/16248

By the way, I don't fully understand the syntax and the purpose of this variable. Is anybody who knows how to populate this variable?

**Comment by itopie** [comment]
I found a way to populate the SESSION_MANAGER variable:

`exec /etc/X11/xinit/xinitrc`

By the way, this does not solve my issue. I wil reinstall the OS.

**Comment by freebs65** [comment]
Attempting to launch screen caster with username freebs, xauthority /home/freebs/.Xauthority, display :0, and args -u freebs /usr/local/bin/Remotely/Desktop/Remotely_Desktop --mode Unattended --host http://some dns or ip --requester-name "" --org-name "somename" --org-id "blah blah blah-871481fac191" --session-id "af038fa2-5560-4176-a6ef-026fb4571993" --access-key "some key".

Re-installing OS won't help.. I've tried a Ubuntu based OS latest version and same thing happens ...I've tried  another Mangro install using Gnome .. same thing... 
No error just sits there...

I'll have to look at MeshCentral as I need access to my home PC/Network.. I have  a Windows 11 VM installed works just fine as a work around.

**Comment by freebs65** [comment]
I've installed rustdesk to access home machines..
if you guyz ever get this to work again on linux/arch . let me know!
I prefer Remotely

**Comment by freebs65** [comment]
Awesome!!.. latest version now works with my Manjaro install.

Not sure if it was updates on my system or the latest version, none the less. it works again!

Thanks!

**Comment by tedtms** [comment]
Same on my end!

**Comment by itopie** [comment]
I confirm that the new release (2023.04.17.1215) works perfectly on Debian 10 (client). Thanks!
