### ISSUE TITLE
Portable Linux client crashes when opening Change Server dialog

### ISSUE THREAD

**Issue by vorbeiei** [immense/Remotely#576]
**Describe the bug**
When trying to access the Change server option the Linux version of the application immediately crashes. I tried this also while debugging from Visual Studio with the same result. The issue started with version v2022.12.31.1910. At the same time another issue came up being, that the window for requesting remote control never comes up on the client, but works just fine on a Windows client.

**To Reproduce**
1. Launch the portable Linux client.
2. Click on the options icon
3. Click on "Change server"
4. application crashes

**Remotely Version**
Server (can be found on about page): 2023.01.20.0732
Agent (can be found in device card): same(I guess since I can't actually connect to the agent but it is downloaded from server)

**Expected Behavior**
No crash when opening settings-dialog.

**Desktop (please complete the following information):**
 - OS: Archlinux, Ubuntu, Linux Mint
 - Browser: Firefox
 - Version: for Ubuntu 22.04.1 LTS

**Additional Context**
The output on the console of the client:
[output.txt](https://github.com/immense/Remotely/files/10527898/output.txt)

**Comment by bmcgonag** [comment]
I have also experienced this with a client running Kubuntu 22.04.1 LTS.
