### ISSUE TITLE
After upgrade, Remotely does not attach the Remotely.db file

### ISSUE THREAD

**Issue by radasys** [immense/Remotely#586]
**Describe the bug**
After upgrading from a non-Docker version to a Docker one and replacing appsettings.json and Remotely.db, Remotely database is empty so existing users cannot log in.

**To Reproduce**
1. You should have "old" appsettings.json and Remotely.db files to replace in /var/www/remotely.
2. Run the container.
3. Try to log in using an existing user.
4. You should get 'Invalid login attempt'.

**Remotely Version**
Upgrade from 2022.09.16.1006 to 2023.02.01.2115

**Expected Behavior**
According to instructions, after replacing Remotely.db and appsettings.json, I should be able to recover my existing settings, users and devices.

**Screenshots**

**Server & Desktop (please complete the following information):**
 - Server OS: Ubuntu 22.04.1
 - Desktop Browser: Google Chrome 110

**Additional Context**
After running an interactive console inside the container and ls -la, I have noticed that appsettings.json file is linked to /remotely-data/appsettings.json. It seems appsettings.json are being honoured because I can register a new user and then I receive the confirmation email and light theme is functioning as well.

![appsettingsjson linked](https://user-images.githubusercontent.com/39229072/217817310-daed1942-d042-4a86-9355-8ec55ea1a9db.png)

However, I believe that as Remotely.db is not linked to /remotely-data/appsettings.json, it is always setting up a new database instead of mine.

![Remotelydb linked](https://user-images.githubusercontent.com/39229072/217817312-cd329252-335a-4838-afb9-e2f6534e8d9a.png)

I don't know if it's related, but maybe can be useful.

Thank you!

**Comment by newuser-k** [comment]
Version: 2022.09.16.1006 upgrade to last one, and same problem, did you find the solution ?

**Comment by radasys** [comment]
Nope, I did not find the solution yet, still researching...

**Comment by shastybsd** [comment]
I copy my Remotely.db to this path: /var/lib/docker/overlay2/e7de516b6cf9f595e1bbcdc276db4e6d9ce1340c6dc17b1507f51cffc6425ee1/diff/app 
My database is running, but i don´t no if its safe.

Here the print of directory content:

![image](https://user-images.githubusercontent.com/27770457/219758686-aef33487-1210-4522-bdba-47b7025a4a9b.png)

**Comment by KodySalak** [comment]
Also having this issue on the most recent docker image... v2023.02.14.2047

**Comment by radasys** [comment]
@shastybsd if you have copied your database inside the container from the outside, it is pretty sure you will have issues the next time you run the container because the database won't persist.

**Comment by KodySalak** [comment]
@radasys FWIW, I did the same thing as @shastybsd. I then redeployed the stack (using Portainer as the FrontEnd on my docker instance) and the volume stayed. Before I saw this thread, when I would follow the documentation, it would obliterate the database.

**Comment by pyredex** [comment]
> @radasys FWIW, I did the same thing as @shastybsd. I then redeployed the stack (using Portainer as the FrontEnd on my docker instance) and the volume stayed. Before I saw this thread, when I would follow the documentation, it would obliterate the database.

Would you mind showing me exactly what you have in portainer? Mine does not persist if I redeploy, thankfully I had a checkpoint on my VM.  Here's what I have (per the directions):

![Capture](https://user-images.githubusercontent.com/40861468/221391248-320be52d-40a2-415f-86a5-89fcf28cd87a.PNG)

**Comment by KodySalak** [comment]
Sure thing!

_In this comment, I am assuming you are in terminal as root, or running as `sudo -i`_

What I did here seemed to persist a stack re-deployment, but your mileage may very.

In Portainer, it doesn't see what you did - this is all on the command line on the docker host. My Volumes look exactly like your screenshot.

I had to:

1. Find info about the container storage that was spawned with the container on the host machine.
`docker ps -a`
`docker container inspect remotely-remotely-1`

2. Look for the `GraphDriver` section and look for the `UppderDir` directory under it
![image](https://user-images.githubusercontent.com/7674269/221392068-cc31d7aa-e09a-42b9-b60a-c13bde167c76.png)

3. cd to app/ in that location
`cd /var/lib/docker/overlay2/%UUIDofStorageFolder%/diff/app`

4. Stop the container in Portainer or CLI

5. Forcibly overwrite the Remotely.db that was in the folder already
`cp /home/localadmin/CorrectRemotely.db ./Remotely.db`

6. Start the container again

AS ALWAYS, I am writing this as a help comment and it assumes no warranty... This is just what I found to work as a workaround. 😁

**Comment by radasys** [comment]
Hi,

We would really like to update to the dockerized version of Remotely.

Are there any updates on this issue? Thanks!

**Comment by lucent-sea** [comment]
> Hi,
> 
> We would really like to update to the dockerized version of Remotely.
> 
> Are there any updates on this issue? Thanks!

I'm not able to reproduce the issue.  Here's a video of me going through the process of creating a new Remotely Docker container and copying over an existing DB and appsettings.


https://user-images.githubusercontent.com/20995508/232809892-e12503d4-0346-4c8f-b352-beb5ffd8decb.mp4

**Comment by lucent-sea** [comment]
Also, please make sure you're using the ImmyBot repo (https://hub.docker.com/r/immybot/remotely) instead of my old personal one.

And, if you're not already, try doing what I did in the video.  Let the container create the files.  Stop the container.  Replace them with your existing files.  Then start it back up.

Let me know if that helps.  :)

**Comment by radasys** [comment]
Hi!

Thank you so much for your answer!

Tomorrow I will test your suggestions!

**Comment by KodySalak** [comment]
@lucent-sea Hello! Thanks for taking the time to look at this. 

I did exactly what you did in your video, it still didn't work 😢.  

Located in the generated "upper dir" found in my above explanation:
```
root@docker:/var/lib/docker/overlay2/29549412bd14ed756fe86dac189a4d526576071f3650bb0cc7dfe72af45a0043/diff/app# ll
total 400
drwxr-xr-x 2 root root   4096 Apr 18 21:10 ./
drwxr-xr-x 5 root root   4096 Apr 18 21:07 ../
lrwxrwxrwx 1 root root     31 Apr 18 21:09 appsettings.json -> /remotely-data/appsettings.json
-rw-r--r-- 1 root root 401408 Apr 18 21:10 Remotely.db
```


Found in my /opt/KSContainers/remotely directory, where I have the compose pointed to:

```
root@docker:/opt/KSContainers/remotely# ll
total 600
drwxrwxr-x 2 localadmin localadmin   4096 Apr 18 21:03 ./
drwxr-xr-x 9 localadmin localadmin   4096 Apr 17 23:12 ../
-rw-r--r-- 1 root       root         1347 Apr 18 21:03 appsettings.json
-rw-r--r-- 1 root       root       602112 Apr 18 21:03 Remotely.db
```

My docker compose:
```
version: "2"
services:
  remotely:
    image: immybot/remotely:latest
    ports:
      - 10.0.10.32:4248:5000
    volumes:
      - /opt/KSContainers/remotely:/remotely-data
    restart: unless-stopped
```

**Comment by lucent-sea** [comment]
@KodySalak  The symbolic link is created for appsettings.json because the dotnet process expects it to be in the same directory as the rest of the binaries.  The database doesn't need a link because we're explicitly modifying the connection string to `/remotely-data/Remotely.db`.

- If you delete the container, empty out `/opt/KSContainers/remotely`, then run the docker container again, does it create the two files in ``/opt/KSContainers/remotely`?
- If you then make changes in the DB, so you see them reflected in Remotely.db?
- If you stop and start the container, does it continue working?
- If you remove and re-run the container, does it continue working?

Every time someone updates their Docker container, it's essentially going through this process.  The container is removed, the files still exist on the host, the new image pulled, and a new container is created that attaches a volume to the existing files.

Considering that it's working for lots of other people and myself, I'm thinking it might be related to your environment.  I'm not familiar with Portainer, but maybe that has something to do with it?  I don't know.

**Comment by KodySalak** [comment]
>If you delete the container, empty out /opt/KSContainers/remotely, then run the docker container again, does it create the two files in /opt/KSContainers/remotely (appsettings.json and Remotely.db)?

Yes, that works as intended.
>If you then make changes in the DB, so you see them reflected in Remotely.db?

The size changes between each restart, so I'm going to assume yes.
>If you stop and start the container, does it continue working?

Yessir!
>If you remove and re-run the container, does it continue working?

Sure does!

One other thing I noticed too - when I had the test container running (using the generated database), I saw the `.db-shm` and the `.db-wa1` files in the `/opt/KSContainers/remotely-temp` directory:
```
localadmin@docker:/opt/KSContainers/remotely-temp$ ll
total 3596
drwxrwxr-x  2 localadmin localadmin    4096 Apr 21 00:12 ./
drwxr-xr-x 10 localadmin localadmin    4096 Apr 21 00:12 ../
-rw-r--r--  1 root       root          1324 Apr 21 00:13 appsettings.json
-rw-r--r--  1 root       root          4096 Apr 21 00:12 Remotely.db
-rw-r--r--  1 root       root         32768 Apr 21 00:13 Remotely.db-shm
-rw-r--r--  1 root       root       3625632 Apr 21 00:13 Remotely.db-wal
```

I do not see those in the production install container directory with the pre-made DB from the old install while the container is running.
```
localadmin@docker:/opt/KSContainers/remotely-temp$ ll ../remotely
total 600
drwxrwxr-x  2 localadmin localadmin   4096 Apr 18 21:03 ./
drwxr-xr-x 10 localadmin localadmin   4096 Apr 21 00:12 ../
-rw-r--r--  1 root       root         1347 Apr 18 21:03 appsettings.json
-rw-r--r--  1 root       root       602112 Apr 18 21:03 Remotely.db
```

I went outside of portainer and made a compose file with vim, did a `docker-compose up` on it, stopped it, replaced the files like you did in your previous post (the one with the video), and restarted - The same thing happened (it didn't take the migrated database, it spun up a "new" one in the `UpperDir` again).

Were there any updates to SQLite from Ubuntu to Docker that would cause an incompatibility issue? I'm just pulling at straws here.

Thanks again for your help :smile:

**Comment by radasys** [comment]
Hi @lucent-sea I have tested again but the issue is still there. It seems it's pulling the configuration from appsettings.json because the theme changes from Dark to Light when I start again the container.

However, I receive an invalid login attempt error when trying to use existing credentials.

BTW, please let me know if I may provide you my DB and appsettings.json files so you can verify.

Thank you for your support!

**Comment by xrpixer** [comment]
I was able to Band-Aid this by removing the packaged DB file and manually adding a symlink from the remotely-data directory -

`docker exec -it remotely bash
rm /app/Remotely.db
ln -s /remotely-data/Remotely.db /app/Remotely.db
exit
docker restart remotely`

This protects the Remotely.db file during an upgrade, like they do with the appconfig.json file.
I assume @immensenet  will have this fixed in one of the next Docker container updates?

**Comment by xrpixer** [comment]
> @KodySalak The symbolic link is created for appsettings.json because the dotnet process expects it to be in the same directory as the rest of the binaries. The database doesn't need a link because we're explicitly modifying the connection string to `/remotely-data/Remotely.db`.

Just saw this. lol
But whatever is supposed to be updating this connection string doesn't seem to work all the time. It certainly didn't change anything on mine when I upgraded.
I followed the README instructions -
>Data for Remotely will be saved in /var/www/remotely/ within two files: appsettings.json and Remotely.db.
>These files will persist through teardown and setup of new Remotely containers.
>If upgrading from a non-Docker version of Remotely, overwrite these files with the ones from your previous installation.

The appsettings.json file from my previous install had it pointed to the same directory, not /remotely-data/Remotely.db.

**Comment by brl33** [comment]
Know how workks jnj.on database but u need to know that Shell or Unix
implement on every coding language .Thats why iv make *invert protocol etc
etc.That looooongvstorry.Point is that Access that is better like Snowden
Case..

pon., 15 maj 2023, 20:57 użytkownik Jordan Weaver ***@***.***>
napisał:

**Comment by lucent-sea** [comment]
> I assume @immense @lucent-sea will have this fixed in one of the next Docker container updates?

Unfortunately, I haven't been able to replicate the issue.  I can only fix something if I have repro steps that consistently replicate it.

I'm constantly upgrading to new versions of the container when I'm developing, sometimes multiple times a day, and I haven't had any issues.

> removing the packaged DB file

There is no packaged DB.  When the app starts, it first loads appsettings.json, then it either creates or loads the DB file in the "SQLite" connection string.  If the DB is getting created in the app root directory, and not in the volume, then it suggests that it's somehow getting the wrong connection string.

If you stop the container and check `appsettings.json` on the host, what are you seeing for the SQLite connection string?  It should be exactly this:  `"SQLite": "DataSource=/remotely-data/Remotely.db",`

**Comment by radasys** [comment]
Dear @lucent-sea,

Have you tried between a non-Docker version and a Docker one? (e.g, upgrading from 2022.09.16.1006 to 2023.02.01.2115).

Thanks!

**Comment by lucent-sea** [comment]
> Dear @lucent-sea,
> 
> Have you tried between a non-Docker version and a Docker one? (e.g, upgrading from 2022.09.16.1006 to 2023.02.01.2115).
> 
> Thanks!

Yeah.  All of my instances were originally "bare metal" and were migrated to Docker.

What's your connection string for SQLite?  It has to be `"SQLite": "DataSource=/remotely-data/Remotely.db"`, since that's where the volume is located.  This will be done automatically if you don't have an existing `appsettings.json` file in the volume.  But if you're copying an existing file first, it needs to be set manually before starting the container.

**Comment by radasys** [comment]
You were totally right. 

If you agree, I have created PR https://github.com/immense/Remotely/pull/635 to clarify this on README.md because I think it would be useful for other users.

**Comment by lucent-sea** [comment]
Thanks for the update and the PR!  :)  I merged it in.
