### ISSUE TITLE
Simple security measures

### ISSUE THREAD

**Issue by modem7** [immense/Remotely#591]
Given that this system might be exposed to the internet, or have other bad actors attempt to brute force the login, on top of the 2fa requirement that's already implemented, would something like a lock out account after x attempts for x period be a useful addition?

**Comment by lucent-sea** [comment]
Thanks for bringing this up.  I thought this was enabled by default with Microsoft's Identity framework templates, but apparently that wasn't the case.  My bad for missing it.

I updated it so it is enabled by default for new accounts.  Accounts will be locked out for 5 minutes after 5 failed attempts (Identity framework's defaults).

Existing accounts will need to be manually updated in the database by changing `LockoutEnabled` to `true` on the `RemotelyUsers` table.
