### ISSUE TITLE
Debian Based Linux: Install..sh fails with "ETag is empty."

### ISSUE THREAD

**Issue by CtheCondor** [immense/Remotely#609]
**Describe the bug**
The install script for Linux is failing. It is failing using both the provided commands with the same Error: "ETag is empty. Aborting install"
```
Example Install:
sudo [path]/Install-Ubuntu-x64.sh
Example Local Install:
sudo [path]/Install-Ubuntu-x64.sh --path [path]/Remotely-Linux.zip
```

**To Reproduce**
1. Download the [Ubuntu x64 Bash Installer](https://remote.condertech.com/API/ClientDownloads/UbuntuInstaller-x64)
2. Open Terminal in Downloads folder
3. Try First Command to run the sh directly
4. Results in a failure; try install [Linux x64 Files Only](https://remote.condertech.com/Content/Remotely-Linux.zip)
5. Repeat with Modified Command
6. Also Fails

**Remotely Version**
Version: 2023.02.14.2047
Agent N/A

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/70120966/223611501-c3572d0c-4937-43d4-93cf-ce8f4cf2ffd0.png)

**Desktop (please complete the following information):**
 - OS: Mx Linux 21
 - Browser NA
 - Version NA

**Smartphone (please complete the following information):**
 - Device: NA
 - OS:  NA
 - Browser  NA
 - Version  NA

**Additional Context**
I believe I know the issue is due to the default script output having a hostname with http vs https but if so its not documented anywhere so hoping this can be quickly confirmed and archived for others who might have this issue to find.

**Comment by lucent-sea** [comment]
Can you try installing `curl` and see if that solves it?  I need to move the installation of it to the beginning of the script.

**Comment by lucent-sea** [comment]
Closing this since there's been no response or other reports.  Also, the install script is only tested on Ubuntu, so it may not work with MX Linux.

**Comment by ExWoomera** [comment]
@CtheCondor I had the same issue trying to install the Remotely client on my Kali.

For me, the issue was with the link to the Remotely server. Open the *.sh file in an editor like Nano and change the Hostname value from "HTTPS" to "HTTP".

**Comment by elightcap** [comment]
I have the opposite problem, where the *.sh has http://... as trhe hostname, when it should be https. can i edit the script directly somewhere?

**Comment by bitbound** [comment]
> I have the opposite problem, where the *.sh has http://... as trhe hostname, when it should be https. can i edit the script directly somewhere?

Please read the following section in the readme.  It explains what's likely misconfigured and how to work around it if you can't get forwarded headers configured correctly.

https://github.com/immense/Remotely?tab=readme-ov-file#important-https-and-reverse-proxies
