### ISSUE TITLE
Project died ?

### ISSUE THREAD

**Issue by osnipezzini** [immense/Remotely#613]
It's been a few weeks since the project has received any updates.

I saw some reports, including myself, that the system does not work, does not save configurations. Reddit doesn't seem to get visits from admins anymore.

Does the build system itself still work?

**Comment by bmcgonag** [comment]
The project is alive and well. The origina author is working with / for Immy-bot on the project, and it seems to get monthly updates. Not sure if he has time to answer on Reddit as much, but it is still moving forward.
I imagine this can be closed @lucent-sea

**Comment by dkattan** [comment]
Closing because IT'S ALIVE
