### ISSUE TITLE
Linux clients (resident agents and one-time clients) not working

### ISSUE THREAD

**Issue by tyounglightsys** [immense/Remotely#617]
I have a copy of Remotely under Ubuntu 2018.04, with the remotely agent file, /usr/local/bin/Remotely/Desktop/Remote_Desktop file having been built on Feb 15, 2023.  When that file is run, it is giving us an error: "No service for type 'Immense.RemoteControl.Desktop.UI.ViewModels.IMessageBoxViewModel' has been registered"

The Remotely_Desktop single-use client (not the Agent), downloaded from the same version of remotely, gives me the same error when run.  Is there something wrong with the build?

**Comment by tyounglightsys** [comment]
I have verified this on Ubuntu 20.04 and 22.04 also.  The Linux client bundled with my version does not work as compiled / linked.

**Comment by lucent-sea** [comment]
I'll soon be resuming work on Remotely in an official capacity (as an employee of ImmyBot).  :)  I don't have an exact timeframe, and I'll have priorities that aren't always specifically related to Remotely.  But it should be in the next couple months, and this one should be a quick fix.  I'll update here when it's done.

Note to self:  `IMessageBoxViewModel` isn't registered in DI.  Make sure there are no others missing as a result of extracting shared code into the RemoteControl library.

**Comment by lucent-sea** [comment]
I pushed up an image under the [experimental tag](https://hub.docker.com/layers/immybot/remotely/experimental/images/sha256-b6d8281e4a5d66674c16dcb27f411d19a3be7359b0f05046ba5c59a1280ed7fc?context=explore).  Both attended and unattended access are working on my Ubuntu machines now.

Let me know if that's working for you, and I'll release them under `latest` next week.  :)

**Comment by tyounglightsys** [comment]
Excellent!  Yes, that worked from my end.   Thanks a ton.

**Comment by tyounglightsys** [comment]
I see the docker file has been updated.  My version has been based off the asset, Remotely_Server_Linux-x64.zip (found on the releases page).  Is it likely the updates will be done as a release, or do I need to figure how to change my system over to using the docker version?

**Comment by lucent-sea** [comment]
I'll release the assets on GitHub soon too.

**Comment by lucent-sea** [comment]
They're up there now. :)

**Comment by tyounglightsys** [comment]
Excellent, those worked for me.  Nice having my Linux boxes showing up when I install the agent.  Thanks a ton.
