### ISSUE TITLE
Enforce Attended Access not working Agent

### ISSUE THREAD

**Issue by Kilian-Schwarz** [immense/Remotely#618]
Hello all,
I have the problem with the Enforce Attended Access that I can't press yes or no. I can't press yes. 

On the client the agent is installed. 
On the server remotely via docker.

Enforce Attended Access is enabled and the request comes to the client but when I press yes or no nothing happens when I look on the server via tcp dump also no packets come from the client when I press yes or no

**Comment by rucksman** [comment]
Some goes for me. Agent is installed in Windows 11 Pro. When the notification pops up on the client machine I can move and close this window, but nothing happing when clicking "Yes" or "No".

**Comment by simonreufsteck** [comment]
Same problem here

**Comment by MaciejStiller** [comment]
Can confirm it also happens for me on server&agent v2023.04.17.1215

**Comment by lucent-sea** [comment]
This should be fixed in the changes I'm working on now.  I'll comment again when a preview image is available.  Probably sometime next week.

**Comment by lucent-sea** [comment]
This should be fixed in the `experimental` tag:

```
docker pull immybot/remotely:experimental
```

I'll keep this open until the `latest` image is updated.  Probably next week.  I'll also do a GitHub release at the same time.

**Comment by lucent-sea** [comment]
This should be fixed in the latest release.
