### ISSUE TITLE
Scripts page no longer reacheable after adding a script in the wrong location

### ISSUE THREAD

**Issue by KawaKode** [immense/Remotely#631]
When in the Scripts page (remotely.domain.com/scripts), if you create a script and set his location in /scripts, the Scripts page becomes completly borked.

1. Go to Scripts on the left menu bar
2. Create a script (any language)
3. Set its location to /scripts
4. Confirm
5. Error in screenshot below happens

**Remotely Version**
Server : 2023.05.03.1256

**Expected Behavior**
The script gets saved.

**Screenshots**
![image](https://github.com/immense/Remotely/assets/75862028/74c628cf-5514-4c96-8553-750bcbde3741)
And after clicking the "reload"button : 
![image](https://github.com/immense/Remotely/assets/75862028/1a639cc4-9016-4245-885f-4a548a09990b)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser : Firefox 113.0.1

**PS** : Only the scripts page is affected by that error, the rest of the app works as if nothing happened, even on a forced refresh or a complete cache+cookies cleaning the issue persists.

**Comment by lucent-sea** [comment]
Thanks for repro steps.  I'll submit a PR and have this in the next release.
