### ISSUE TITLE
Scripts not running

### ISSUE THREAD

**Issue by Surgical17** [immense/Remotely#646]
**Describe the bug**
Scripts not running on device where a Remotely agent is installed

**To Reproduce**
Create a script as shown in screenshot. Script does not run. 
I did run the same command manually in CMD on the devices and it worked.
I am also able to remotely connect to the devices, so there is a connection

**Remotely Version**
Server: Version: 2023.05.03.1256
Agent: 2023.05.03.1256

**Expected Behavior**
To run the Script

**Screenshots**
![image](https://github.com/immense/Remotely/assets/76941635/c8db2e7a-f856-4e4c-9702-c5e12510c241)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Edge
 - Version Latest

**Additional Context**
I need a way to test if scripts is working. Once it is I want to set up scripts to install chocolaty and then install apps via chocolaty

**Comment by Surgical17** [comment]
Issue solved:
In some cases its important to change the directory from "Program Files\Remotely" to "Windows\System32" by adding teh following to the start of the script:
cd "C:\Windows\System32"

**Comment by brl33** [comment]
In som cases u enter in root direct file open property and chk who had a admin user oermmision after chk who and what knd of cert asgned that file After opn process info and chk how program react after all..
