### ISSUE TITLE
Lose inpute after change keyboard layout

### ISSUE THREAD

**Issue by DeAlexPesh** [immense/Remotely#656]
Hi. Can you fix bug? After press hotkey for change kb layout on different from the one that was when connected, input is broken until you change it back. Thx.

**Comment by Ivan-Dobro** [comment]
Same here (

**Comment by sshnevis** [comment]
yeap. sometimes keyboard not working and only numbers sent to client,

**Comment by Natan738** [comment]
I have the same problem, it does not send commands such as win+R, accent on the letters, exclamation point and others.

**Comment by licenceit** [comment]
In my case it could be fixed by executing Ctrl+Alt+Del in remotely menu (arrow menu where you have file share ect.).
After it I can again use mouse and keyboard. I dont know if its same problem but it looks similar.

**Comment by DeAlexPesh** [comment]
> In my case it could be fixed by executing Ctrl+Alt+Del in remotely menu (arrow menu where you have file share ect.). After it I can again use mouse and keyboard. I dont know if its same problem but it looks similar.

it's a not normal...

**Comment by licenceit** [comment]
> > In my case it could be fixed by executing Ctrl+Alt+Del in remotely menu (arrow menu where you have file share ect.). After it I can again use mouse and keyboard. I dont know if its same problem but it looks similar.
> 
> it's a not normal...

No it's not you'r right it's bug, but this is opensource aplication in development beta version so there are some problems. I wrote it because it's easy and fast fix at that moment so you didnt need to reconect or change layout back. I never said it's normal. Thats only help information, not complete fix.

**Comment by bitbound** [comment]
This issue has been grouped under pinned issue #688 .  Please comment there if you're still having issues in the latest release.
