### ISSUE TITLE
Update Agent

### ISSUE THREAD

**Issue by Surgical71** [immense/Remotely#659]
**Is your feature request related to a problem? Please describe.**
After updating to the latest version, my Agents showed it was out of date, but it was still connected to Remotely. A way to update the agents would be helpful

**Describe the solution you'd like**
A button that will update the agent.

**Describe alternatives you've considered**
A script to update the agent

**Additional context**
If anyone already has a working script to update the agent please share.

**Comment by lucent-sea** [comment]
You can update all outdated agents on the Server Config page:

![image](https://github.com/immense/Remotely/assets/20995508/0e95d5ff-30ea-4ae4-a8bf-9e16f43cfa4e)

However, keep in mind that if the agent isn't auto-updated, that means there was a problem the first time it tried.  When this happens, it will wait 24 hours (or if the computer/service is restarted) before attempting to auto-update again.  This is to prevent a bad update from causing a constant cycle of auto-updating, which would consume bandwidth, strain the server, and make it difficult to diagnose the issue remotely.

In my experience, it's usually something harmless, like a temporary connectivity interruption with the server while downloading or locked file on the agent.  But it's often worth checking out before hitting the Update All button.

You can check the agent's logs for the current day directly from the web app.  It's in the Device Details page, under the Remote Logs tab.
