### ISSUE TITLE
scripts not running

### ISSUE THREAD

**Issue by tombrugmans** [immense/Remotely#664]
**Describe the bug**
I can't get any script to run using the run script option or the script schedules option. Running the same script using the quick script option works fine however. after running the script it doesn't show in the device script history or when I download the script history log.

**To Reproduce**
Create a script and try to run it using the run script menu.

**Remotely Version**
Server version: 2023.06.19.0759 but I already had this issue on version v2023.02.01.2115 (or earlier but this is when I noticed it.)
Agent: 2023.06.19.0759

**Expected Behavior**
The script runs using the schedule or run script options.

**Screenshots**
![image](https://github.com/immense/Remotely/assets/133379846/ba641de4-8d34-4e6f-bed7-f867e777b27e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 114.0.1 (64-bit)

- [x] I am running Remotely in Docker and not on my QNAP, Synology, or Internet Connected Toaster

**Comment by bitbound** [comment]
This has been fixed in PR #670 .   It's been published to the `preview` tag in Docker Hub and will be pushed to `latest` on the next full release.

**Comment by bitbound** [comment]
This should be fixed in the latest release.  Please comment and reopen if not.
