### ISSUE TITLE
Keyboard mapping

### ISSUE THREAD

**Issue by FabienFR17** [immense/Remotely#673]
hi,

When I hit a key on the numeric keypad, for example 1, the character sent is the one that corresponds to key 1 on the main keyboard. On a French keyboard, it corresponds to &.
If I type 123456 on the numeric keypad, I get &é"'(-

**Remotely Version**
Server : 2023.05.24.0927 (docker image)
Agent :  2023.05.24.0927

**Desktop / Remote **
 - OS: Windows 10 (remote: all Windows)
 - Browser : Opera
 - Version 99

- I am running Remotely in Docker and not on my QNAP, Synology, or Internet Connected Toaster

**Comment by bitbound** [comment]
This issue has been grouped under pinned issue #688 .  Please comment there if you're still having issues in the latest release.
