### ISSUE TITLE
Remote screens not working

### ISSUE THREAD

**Issue by Theknight2015** [immense/Remotely#686]
I updated my docker remotely image to the latest version today and while everything else seems to still work, when I go to a device or if I go to the remote control tab, all I get is a weird layout in the top left corner. I have attached a picture of the screen shown when clicking on the "Remote Control" tab. It used to show a box where you could enter the device info and control it that way but now it doesn't.

![chrome_6g83j4Ra77](https://github.com/immense/Remotely/assets/117456049/b5d851ae-d42d-499e-8e29-12d1b88e502c)

Any help would be greatly appreciated.

**Comment by bitbound** [comment]
I'm guessing this is due to stale CSS files being cached.  Try clearing your cache and reloading.  I think the shortcut for that is Ctrl+F5.

**Comment by Theknight2015** [comment]
> I'm guessing this is due to stale CSS files being cached. Try clearing your cache and reloading. I think the shortcut for that is Ctrl+F5.

I tried doing that several times on several different browsers and it did not work. I finally did figure out the issue and it makes total sense now that I think about it. I was 1 version behind on my main docker installation which apparently was an issue because the newest version of docker uses an updated version of "Something I can't remember off the top of my head" so that new version was used to compile the newest release of remotely. Because of the difference, my remotely docker instance was out of date compared to the docker instance it was running on and it gave me several odd errors. Once I updated docker and then re-pulled the latest image of remotely, I re-ran that image to update the container and then everything worked.

Not sure why I didn't think of that prior to posting on here but hopefully it will help anyone else who runs into the same issue I did.

I appreciate your time and response, thank you!

**Comment by bmcgonag** [comment]
It sounds like this can be closed @Theknight2015 and @lucent-sea .

**Comment by bitbound** [comment]
Thanks for the updates, @Theknight2015 and @bmcgonag .
