### ISSUE TITLE
Error with CoreCLR

### ISSUE THREAD

**Issue by vantzs** [immense/Remotely#768]
Full Error in Container:
Entered main script.
Starting Remotely server.
Failed to create CoreCLR, HRESULT: 0x80070008

I'm attempting to run Remotely in a Docker Container
Host is Ubuntu 20.04
Docker version is Docker version 20.10.7, build f0df350
2 Xeon Cores, 16 GB's of RAM to the docker container
Networking is in bridged mode
No Reverse proxy, can't get container to start properly

**Comment by vantzs** [comment]
In case anyone else has this issue, I was running Ubuntu 20.04 and the fix was to do a release upgrade on Ubuntu to 22.04 followed by a full upgrade of docker to the latest version. Once that was done, the container ran as expected.

**Comment by PmPPolska** [comment]
#No

https://network.tptool.pro/?utm_source=tokenpocket#/

sob., 20 sty 2024, 7:39 AM użytkownik Vantz Stockwell <
***@***.***> napisał:
