### ISSUE TITLE
PC disconnected after some time

### ISSUE THREAD

**Issue by michaelmittermair** [immense/Remotely#773]
Installing the client on Windows 11 runs without any problems. Also the client connects to the server and is shown as active.
After some time, the client gets offline on the website. There is no error in the logs or the event log.

In the logs there is a successful versioncheck about every 90 seconds:

[Information]	[v2023.09.11.1010]	[Process ID: 3664]	[Thread ID: 25]	[2023-11-23 20:25:32.219]	[Remotely.Agent.Services.Windows.UpdaterWin]	Service Updater: Version is current.	
[Information]	[v2023.09.11.1010]	[Process ID: 3664]	[Thread ID: 26]	[2023-11-23 20:27:05.311]	[Remotely.Agent.Services.AgentHubConnection]	Reconnected to server.	

Sometimes, the clients connects again after some time, but most of the time, the client keeps beeing offline.
Restarting the windows service and the client connects correctly to the server, but after some time it disconnects again.

Any idea, why it's always disconnecting?

**Comment by huntson** [comment]
Same here with intermittent disconnects.  Just starting using this and I really like the potential but this is a non-starter.

**Comment by CFox243** [comment]
> Installing the client on Windows 11 runs without any problems. Also the client connects to the server and is shown as active. After some time, the client gets offline on the website. There is no error in the logs or the event log.
> 
> In the logs there is a successful versioncheck about every 90 seconds:
> 
> [Information] [v2023.09.11.1010] [Process ID: 3664] [Thread ID: 25] [2023-11-23 20:25:32.219] [Remotely.Agent.Services.Windows.UpdaterWin] Service Updater: Version is current. [Information] [v2023.09.11.1010] [Process ID: 3664] [Thread ID: 26] [2023-11-23 20:27:05.311] [Remotely.Agent.Services.AgentHubConnection] Reconnected to server.
> 
> Sometimes, the clients connects again after some time, but most of the time, the client keeps beeing offline. Restarting the windows service and the client connects correctly to the server, but after some time it disconnects again.
> 
> Any idea, why it's always disconnecting?

are you running through a proxy server?

**Comment by huntson** [comment]
On my end it does appear to be the proxy that is the issue.  Perhaps you can recommend some headers that need to be modified/adjusted in order to get this to stay working all the time?

**Comment by CFox243** [comment]
if using nginx proxy
```
   location / {
        proxy_pass         http://ip:5000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_send_timeout 30m;
        proxy_connect_timeout 3600s;
        proxy_read_timeout 30m;
        client_max_body_size 10M;
    }
    location /_blazor {	
        proxy_pass http://ip:5000;
        proxy_http_version 1.1;	
        proxy_set_header Upgrade $http_upgrade;	
        proxy_set_header Connection "upgrade";	
        proxy_set_header Host $host;	
        proxy_cache_bypass $http_upgrade;	
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;	
        proxy_set_header   X-Forwarded-Proto $scheme;	
        proxy_send_timeout 30m;
        proxy_connect_timeout 3600s;
        proxy_read_timeout 30m;
        client_max_body_size 10M;
    }	
    location /AgentHub {	
        proxy_pass   http://ip:5000;
        proxy_http_version 1.1;	
        proxy_set_header Upgrade $http_upgrade;	
        proxy_set_header Connection "upgrade";	
        proxy_set_header Host $host;	
        proxy_cache_bypass $http_upgrade;	
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;	
        proxy_set_header   X-Forwarded-Proto $scheme;	
        proxy_send_timeout 30m;
        proxy_connect_timeout 3600s;
        proxy_read_timeout 30m;
        client_max_body_size 10M;
    }	
    location /ViewerHub {	
        proxy_pass   http://ip:5000;
        proxy_http_version 1.1;	
        proxy_set_header Upgrade $http_upgrade;	
        proxy_set_header Connection "upgrade";	
        proxy_set_header Host $host;	
        proxy_cache_bypass $http_upgrade;	
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;	
        proxy_set_header   X-Forwarded-Proto $scheme;	
        proxy_send_timeout 30m;
        proxy_connect_timeout 3600s;
        proxy_read_timeout 30m;
        client_max_body_size 10M;
    }	
    location /CasterHub {	
        proxy_pass   http://ip:5000;
        proxy_http_version 1.1;	
        proxy_set_header Upgrade $http_upgrade;	
        proxy_set_header Connection "upgrade";	
        proxy_set_header Host $host;	
        proxy_cache_bypass $http_upgrade;	
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;	
        proxy_set_header   X-Forwarded-Proto $scheme;	
        proxy_send_timeout 30m;
        proxy_connect_timeout 3600s;
        proxy_read_timeout 30m;
        client_max_body_size 10M;
    }
```

**Comment by huntson** [comment]
It's not just one of those- they all need to be in place?

**Comment by PmPPolska** [comment]
Because u had a set firewall like strict...Set him like weak....Give perm
to  apps from unknown....And instal wireshark

#brl33

czw., 23 lis 2023, 20:34 użytkownik Michael Mittermair <
***@***.***> napisał:

**Comment by michaelmittermair** [comment]
> if using nginx proxy
> 
> ```
>    location / {
>         proxy_pass         http://ip:5000;
>         proxy_http_version 1.1;
>         proxy_set_header   Upgrade $http_upgrade;
>         proxy_set_header   Connection keep-alive;
>         proxy_set_header   Host $host;
>         proxy_cache_bypass $http_upgrade;
>         proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header   X-Forwarded-Proto $scheme;
>         proxy_send_timeout 30m;
>         proxy_connect_timeout 3600s;
>         proxy_read_timeout 30m;
>         client_max_body_size 10M;
>     }
>     location /_blazor {	
>         proxy_pass http://ip:5000;
>         proxy_http_version 1.1;	
>         proxy_set_header Upgrade $http_upgrade;	
>         proxy_set_header Connection "upgrade";	
>         proxy_set_header Host $host;	
>         proxy_cache_bypass $http_upgrade;	
>         proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;	
>         proxy_set_header   X-Forwarded-Proto $scheme;	
>         proxy_send_timeout 30m;
>         proxy_connect_timeout 3600s;
>         proxy_read_timeout 30m;
>         client_max_body_size 10M;
>     }	
>     location /AgentHub {	
>         proxy_pass   http://ip:5000;
>         proxy_http_version 1.1;	
>         proxy_set_header Upgrade $http_upgrade;	
>         proxy_set_header Connection "upgrade";	
>         proxy_set_header Host $host;	
>         proxy_cache_bypass $http_upgrade;	
>         proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;	
>         proxy_set_header   X-Forwarded-Proto $scheme;	
>         proxy_send_timeout 30m;
>         proxy_connect_timeout 3600s;
>         proxy_read_timeout 30m;
>         client_max_body_size 10M;
>     }	
>     location /ViewerHub {	
>         proxy_pass   http://ip:5000;
>         proxy_http_version 1.1;	
>         proxy_set_header Upgrade $http_upgrade;	
>         proxy_set_header Connection "upgrade";	
>         proxy_set_header Host $host;	
>         proxy_cache_bypass $http_upgrade;	
>         proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;	
>         proxy_set_header   X-Forwarded-Proto $scheme;	
>         proxy_send_timeout 30m;
>         proxy_connect_timeout 3600s;
>         proxy_read_timeout 30m;
>         client_max_body_size 10M;
>     }	
>     location /CasterHub {	
>         proxy_pass   http://ip:5000;
>         proxy_http_version 1.1;	
>         proxy_set_header Upgrade $http_upgrade;	
>         proxy_set_header Connection "upgrade";	
>         proxy_set_header Host $host;	
>         proxy_cache_bypass $http_upgrade;	
>         proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;	
>         proxy_set_header   X-Forwarded-Proto $scheme;	
>         proxy_send_timeout 30m;
>         proxy_connect_timeout 3600s;
>         proxy_read_timeout 30m;
>         client_max_body_size 10M;
>     }
> ```

This helped and I was able to fix this issue with this config
