### ISSUE TITLE
Multiple issues with latest version

### ISSUE THREAD

**Issue by tim1014** [immense/Remotely#819]
**Describe the bug**
1. Max Organization Count (max=1 and only 1) reached but still able to register
2. Add a non-registered user would not go into invitations and send e-mail, but straight into user list
3. Reset password e-mail would never send

**To Reproduce**
Issue 1:
1. Confirm "Max Organization Count" = 1 in server config page
2. Logout and start register as an new user
3. New user should be registered with a new organization and (why?) no e-mail verification required.

Issue 2:
1. Go to "Organization", add a new user (non-registered) at the bottom
2. User straight into "Users" list rather than "Invitations" list.

Issue 3:
1. Logout, at login page click forget password, enter an registered user e-mail address
2. Show forget password e-mail successfully sent but never received and no logging in server logs

**Remotely Version**
Server (can be found on about page): 2024.02.22.1231
Agent (can be found in device card): N/A

**Expected Behavior**
Issue 1: On register page should show "Registration is disable" or sth similar
Issue 2: Non-registered user should create an invitation instead of creating a new user entry
Issue 3: Reset password e-mail should be sent to designated e-mail address

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [e.g. chrome, safari] Chromium
 - Version [e.g. 22] 122.0.6261.70

**Additional Context**
A freshly install remotely docker instance without any middleware

- [X] I am running Remotely in Docker and not on my QNAP, Synology, or Internet Connected Toaster

**Comment by PmPPolska** [comment]
Server start action who ur can read as a %startChellange

sob., 24 lut 2024, 02:28: Astik ***@***.***> napisał(a):

**Comment by bitbound** [comment]
Thanks for the report!

edb4bc54b85d3b97599996825f3f536fc3fa8055 should address number 1.
7478d6333ee2db255ba068f278706b02f3837720 should address number 3.

Number 2 is by design.  It's been that way for a while.

These will go out in the next release.

**Comment by tim1014** [comment]
> Thanks for the report!
> 
> [edb4bc5](https://github.com/immense/Remotely/commit/edb4bc54b85d3b97599996825f3f536fc3fa8055) should address number 1. [7478d63](https://github.com/immense/Remotely/commit/7478d6333ee2db255ba068f278706b02f3837720) should address number 3.
> 
> Number 2 is by design. It's been that way for a while.
> 
> These will go out in the next release.

Confirm issue 1 and 3 are fixed. Thanks for the quick update ❤️

**Comment by PmPPolska** [comment]
⊶⊑∷⌊∴⊹∵⌉∷⊒⊷

wt., 27 lut 2024, 04:01: Astik ***@***.***> napisał(a):

**Comment by PmPPolska** [comment]
The Remotely.db file is not in /app/AppData but rather in /app/

---------- Forwarded message ---------
From: ***@***.***>
Date: sob., 2 mar 2024, 21:47
Subject: Re: W Wzwiązku ze sprawąUM35/E001000000/001732304-1
To: ***@***.***>


Cześć,

dziękujemy za kontakt z Google.

Twój e-mail trafił na adres, którego już nie sprawdzamy.
Aby uzyskać pomoc, otwórz https://support.google.com/.

**Comment by PmPPolska** [comment]
----------------

sob., 2 mar 2024, 21:50: Karol Pawłowski ***@***.***>
napisał(a):

> The Remotely.db file is not in /app/AppData but rather in /app/
>
> ---------- Forwarded message ---------
> From: ***@***.***>
> Date: sob., 2 mar 2024, 21:47
> Subject: Re: W Wzwiązku ze sprawąUM35/E001000000/001732304-1
> To: ***@***.***>
>
>
> Cześć,
>
> dziękujemy za kontakt z Google.
>
> Twój e-mail trafił na adres, którego już nie sprawdzamy.
> Aby uzyskać pomoc, otwórz https://support.google.com/.
>

**Comment by PmPPolska** [comment]
K.J.Pawłowski

sob., 2 mar 2024, 23:14 użytkownik Karol P ***@***.***>
napisał:

>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> ----------------
>
> sob., 2 mar 2024, 21:50: Karol Pawłowski ***@***.***>
> napisał(a):
>
>> The Remotely.db file is not in /app/AppData but rather in /app/
>>
>> ---------- Forwarded message ---------
>> From: ***@***.***>
>> Date: sob., 2 mar 2024, 21:47
>> Subject: Re: W Wzwiązku ze sprawąUM35/E001000000/001732304-1
>> To: ***@***.***>
>>
>>
>> Cześć,
>>
>> dziękujemy za kontakt z Google.
>>
>> Twój e-mail trafił na adres, którego już nie sprawdzamy.
>> Aby uzyskać pomoc, otwórz https://support.google.com/.
>>
>
