### ISSUE TITLE
Registration is not disabling, multiple orgs created

### ISSUE THREAD

**Issue by Verhelsting** [immense/Remotely#822]
Apologies, created an account to report this. I am not versed in github etiquette yet. 
I use Remotely on unraid, as a docker.

Recent update has allowed for multiple registration and multiple orgs to be created. Setting the org count does not fix this nor disable the registration from the home page.

**Comment by tim1014** [comment]
#819 fixed

**Comment by bitbound** [comment]
This should be fixed in the latest image.
