### ISSUE TITLE
[FEATURE_REQUEST] Option to Disable User Registrations with Administrator-Manual Account Creation

### ISSUE THREAD

**Issue by deffcolony** [immense/Remotely#823]
# Is your feature request related to a problem? Please describe.
There is a need for an option in Remotely to disable new user registrations to prevent spam and unwanted account creation. Currently, the absence of such a feature can lead to issues with the quality of user-generated content and potential misuse of the platform.

# Describe the solution you'd like
I propose the implementation of an admin-controlled setting within Remotely that allows the administrator to toggle user registrations on or off. When user registrations are disabled, the public will not be able to create new accounts independently. However, the administrator should retain the ability to manually create user accounts upon request, ensuring a controlled and secure environment.

# Describe alternatives you've considered
An alternative approach could involve implementing a CAPTCHA system during the registration process to mitigate spam. However, this might not be foolproof, and disabling registrations altogether provides a more robust solution to prevent unwanted account creation. Another option could be a user approval system, where new registrations require manual approval from the administrator, but this might introduce delays in the onboarding process.

# Additional context
It would be beneficial to have an additional layer of control over user registrations to enhance the overall security and integrity of Remotely This feature would be particularly useful for instances where the administrator wants to limit access to a specific user base or control the rate at which new accounts are created. Providing the administrator with the ability to create user accounts on request ensures that legitimate users can still access the platform while maintaining a spam-free registration process.

**Comment by PmPPolska** [comment]
—
#[1521]

pon., 26 lut 2024, 15:46: deffcolony ***@***.***> napisał(a):

**Comment by bitbound** [comment]
This was already a feature, but wasn't working two releases back due to a bug.  It's been fixed in the latest release.

It's controlled by the "Max Organization Option" on the Server Config page.  By default, it's set to 1, so registration will be disabled after creating the first account (i.e. your server admin account).  You can set it to a specific number, or set to -1 for unlimited.
