### ISSUE TITLE
BUG - Install-Remotely.ps1 fails with error

### ISSUE THREAD

**Issue by bcurran3** [immense/Remotely#835]
Hi. New guy here. Just installed Remotely in Docker yesterday and am testing.

Resident Agents Windows Installer (x64/x86) Install-Remotely.ps1 fails upon checking headers:

```
Set-ExecutionPolicy Bypass -Scope Process -Force; .\Install-Remotely.ps1
Install/uninstall logs are being written to "C:\Users\bcurran\AppData\Local\Temp\Remotely_Install.txt"
Install started.
Error occurred: At C:\Users\bcurran\Downloads\Install-Remotely.ps1:107 char:18
+ ... dResponse = Invoke-WebRequest -Uri "$HostName/Content/Remotely-Win-$P ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exiting...
```

I bypassed the header check and I can install:

```
function Install-Remotely {
#	$HeadResponse = Invoke-WebRequest -Uri "$HostName/Content/Remotely-Win-$Platform.zip" -Method Head -UseBasicParsing
#	$ETag = $HeadResponse.Headers["ETag"]
#	if (!$Etag) {
#		Write-Host "Failed to get ETag from server.  Aborting install."
#	}
```

**Remotely Version**
Server 2024.02.23.1927:
Agent 2024.02.23.1927:

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Enterprise
 - Version: 10.0.22631 N/A Build 22631
 - PowerShell version:
```
$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

- [x] I am running Remotely in Docker and not on my QNAP, Synology, or Internet Connected Toaster
-

**Comment by rick8413** [comment]
Hi, got the same problem today. 
I did solve this modifying the  Install-Remotely.ps1 file !
The $hostname was "http://xxx.mydomain.com", replacing it with HTTPS (of course) and it started to work perfectly :)

line 23 : 
             [string]$HostName = "http://xxx.mydomain.com" 
      =>  [string]$HostName = "https://xxx.mydomain.com"

It impacts the line 107, coz of this var $HostName.

Hopes this helps.

**Comment by bitbound** [comment]
This will happen if forwarded headers or KnownProxies isn't configured correctly.  As a workaround, you can enable `Force Client HTTPS` in the Server Config page.
