### ISSUE TITLE
BUG - Windows x64/x86 Files Only Resident Agents have no installer (Server 2024.02.23.1927)

### ISSUE THREAD

**Issue by bcurran3** [immense/Remotely#837]
Remotely Version
Server 2024.02.23.1927
Agent 2024.02.23.1927

There is no Remotely_Installer.exe in the .zip packages to run per instructions.

![image](https://github.com/immense/Remotely/assets/14026600/b5634269-a936-4f89-a495-ec631c458320)

![image](https://github.com/immense/Remotely/assets/14026600/878d9aa5-b936-4f7a-a56d-b1fd94e19e97)

Running the Remotely_Agent.exe results in this:
![image](https://github.com/immense/Remotely/assets/14026600/3ede9025-1353-4294-a47d-5faef2b2f572)

Remotely Version
Server 2024.02.23.1927
Agent 2024.02.23.1927

- [X] I am running Remotely in Docker and not on my QNAP, Synology, or Internet Connected Toaster

**Comment by emtec-jim** [comment]
The instructions haven't been updated as yet but the EXE installer no longer exists. It's a powershell script that's used to install the resident agent now - download and run from Powershell.

**Comment by bitbound** [comment]
This was my mistake.  I forgot to update the downloads page to reflect the change.  I'll get it in the next release.

**Comment by sumsupdev** [comment]
There are no zip files to download, the powershell script tries to download the zip package and gets 404
