### ISSUE TITLE
FEATURE REQUEST: Create tunnels for other remote control programs (RDP/VNC/etc)

### ISSUE THREAD

**Issue by bcurran3** [immense/Remotely#839]
I would love to see support for the Remotely Agents to support a tunnel or proxy and reflector to use other remote control programs such as xVNC, RDP, or others. 

Don't get me wrong, I love what Remotely can do, but running in a browser is not as fast or full featured as a more mature discrete program such as using RDP/Remote Desktop. 

OK, I'll be 100% honest - It's driving me crazy that my mouse's back button doesn't work in Chrome over a Remotely session. 😂😂😂😂😂😂😂😂

**Comment by emtec-jim** [comment]
I'm actually very much against this - part of the reason we chose Remotely is that it does not have these capabilities. That makes it far, far easier to handle from a security perspective as I don't need to worry about some miscreant finding a way to abuse proxy functionality on client machines. It also means I can be 100% sure that all agent's activities are recorded for auditing - something we'd lose if there were proxy capabilities.

**Comment by bitbound** [comment]
I started creating this in one of my personal projects, [ControlR](https://github.com/bitbound/ControlR).  This isn't something we'll bring into Remotely, though.
