### ISSUE TITLE
FEATURE REQUEST: smaller agent for windows 

### ISSUE THREAD

**Issue by Giuseppe-TD** [immense/Remotely#859]
when i download the agent in windows it's 80 mb, and it's huge
maybe try to reduce the agent and this will be perfect :D

**Comment by bitbound** [comment]
The majority of the size comes from the .NET Runtime, PowerShell SDK, and Avalonia UI.  NuGet packages account for most of the rest.  The Remotely code itself is a small fraction of the overall size.  There's nothing that can be cut out.  Assembly trimming won't work with this project.

The .NET Runtime is bundled with the app, so it doesn't have to be installed ahead of time. 

Same with the PowerShell SDK.

Avalonia is needed for cross-platform UI.
