### ISSUE TITLE
Add More Modern TLS Support for Install-Remotely.ps1 

### ISSUE THREAD

**Issue by anedward01** [immense/Remotely#899]
**Describe the bug**

In the Install-Remotely.ps1 script, there is a hardcode to only support tls1.2 located at line 20:

`[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12`

My environment only supports tls1.3 connections which was causing the script to error out. To remedy this, I replaced line 20 with the following:

`[Net.ServicePointManager]::SecurityProtocol = "tls13, tls12"`

This allowed me to successfully download and install the application. It's not the best code, but it works well enough for what it serves.

**To Reproduce**
1. Set up a proxy that only supports TLS1.3 (Cloudflare custom settings in my case)
2. Attempt to run the script
3. Run into a generic error on line 107
4. Run only the line 107 snippet
5. Get a TLS/SSL error

**Remotely Version**
Server (can be found on about page): 2024.02.23.1927
Agent (can be found in device card): 2024.02.23.1927

**Expected Behavior**

When running the install script, the Invoke-WebRequest should successfully process.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 127

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional Context**

- [ X] I am running Remotely in Docker and not on my QNAP, Synology, or Internet Connected Toaster

**Comment by bitbound** [comment]
Added in the [latest release](https://github.com/immense/Remotely/releases/tag/v2024.06.27.1520).
