### ISSUE TITLE
Docker: ResetPassword link uses wrong hostname

### ISSUE THREAD

**Issue by Daniel-Hillenbrand** [immense/Remotely#904]
Users are unable to reset password because password reset link sent by mail shows wrong hostname when running official Remotely docker image.

Example: http://localhost:5000/Account/ResetPassword?...

**Comment by bitbound** [comment]
Unable to repro on my instance (using latest Docker image and proxied through Cloudflare).   This is likely due to misconfiguration of [forwarded headers or KnownProxies](https://github.com/immense/Remotely?tab=readme-ov-file#important-https-and-reverse-proxies).
