### ISSUE TITLE
What's with Docker Tags?

### ISSUE THREAD

**Issue by darkpixel** [immense/Remotely#906]
There doesn't seem to be any sort of standardization on docker tags.

We decided to try Remotely last week.
We installed ```immybot/remotely:latest```, got it configured and working.
We started playing with it.

This morning I decided to update the resources associated with the deployment, and everything restarted...and crashed due to TLS errors.

Suspecting a bad new release, I went digging through docker hub to find the previous version.

Why are there tags like '116' and '117' pushed a month ago, but also tags like '1353' pushed a year ago?  And how do those correlate to releases on GitHub like v2024.06.27.1520 or v2024.02.23.1927?

This makes deploying Remotely and rolling back in case of bugs extremely difficult.

**Comment by bitbound** [comment]
The tags got reset when I moved the CI/CD pipeline out of my personal account and into Immense's.  I just now deleted the old tags that were pushed from my pipeline.

The date-based versioning was an unfortunate decision I made a long time ago and never got around to changing.  They don't correlate to the tags, which are simply the build numbers.

**Comment by darkpixel** [comment]
There shouldn't be a problem with date-based tags.  I have several internal projects that use date-based tags.

So how do I correlate releases to build numbers so I can install a specific release if there's a problem?

**Comment by bitbound** [comment]
Currently, you'd have to manually correlate them by looking at the publish dates.

If a future maintainer wants to update this, they can update the release pipeline to use a shared variable to use as the tag on both the GitHub and Docker releases.
