### ISSUE TITLE
Feature Request: Software Install Component using winget or choco

### ISSUE THREAD

**Issue by Nerdy-Technician** [immense/Remotely#922]
**Is your feature request related to a problem? Please describe.**
Feature request

**Describe the solution you'd like**
An option to deploy software to a machine with winget without having to use script but have user freindly names for the apps 

**Describe alternatives you've considered**
Winget scripts however its not sustainable for my agents

**Comment by dkattan** [comment]
Hey @Brandon-Roff checkout https://immy.bot/ it has Remotely’s Remote Control engine built in and is designed for software installation and configuration.

**Comment by Nerdy-Technician** [comment]
Good Afternoon,

no i mean for remotely I can warrant $400 I would like to see it in remotely

**Comment by Nerdy-Technician** [comment]
Please dont close the case until i am happy please

**Comment by Nerdy-Technician** [comment]
Can we please reopen this case
