### ISSUE TITLE
Windows installers not found in downloads

### ISSUE THREAD

**Issue by sumsupdev** [immense/Remotely#953]
when I try to download the windows or any installer either zip or exe it's a page not found
https://localhost:5001/Content/Remotely-Win-x64.zip
i checked the Content folder of the project 
![image](https://github.com/user-attachments/assets/d3a428ab-30ae-460f-9125-3413b746b0af)
There is no zip or exe to download. How do i fix this ?

**Comment by sumsupdev** [comment]
resolved, had to run the publish script

**Comment by jankkm** [comment]
Same problem here. What script did you run?
